// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Post struct {
	PostID    int32     `json:"postID"`
	UserID    int64     `json:"userID"`
	CreatedAt time.Time `json:"createdAt"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}
